version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: farmers_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmers
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./farmers.sql:/docker-entrypoint-initdb.d/farmers.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  flask_app:
    build: .
    container_name: farmer_system_app
    environment:
      FLASK_APP: main.py
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: farmers
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: python main.py

volumes:
  mysql_data:
